<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOSmGhx2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOSmGhx2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOSmGhx2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOSmGhx2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOSmGhx2\App_KernelDevDebugContainer([
    'container.build_hash' => 'OSmGhx2',
    'container.build_id' => '4e6bd619',
    'container.build_time' => 1729867825,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOSmGhx2');
